### ISSUE TITLE
To me this is less clear than Ok(())

### ISSUE THREAD

**Issue by andywwright** [MathiasPius/fallible-option#2]
Normally I would not comment on something that I don't understand why people are doing, but in reply to "Feedback and comments are extremely welcome" I thought you might want to hear an opposite opinion.

To me this doesn't simplify things, on the contrary it adds unnecessary cognitive overhead of learning yet another type. In case of `Ok(())` at least you can clearly see that you return nothing wrapped in `Result`. In case of `Success` on the other hand you explicitly return SOMETHING from a function that "clearly produces no output value" and this is much more counterintuitive.

I think if one seeks to seemingly not return the unit `()` type - [Fehler](https://github.com/withoutboats/fehler) is the way to go. This is the only way of not typing any return in both the signature and the body and still have the "?" shortcut that I'm aware of:

```
#[throws(OtherError)]
fn do_thing() {
    might_fail()?;
}
```

**Comment by MathiasPius** [comment]
I appreciate your input. I see your point about cognitive overhead, but I can't immediately concede it. I think the argument that fewer types equal less cognitive overhead can be proved invalid quite trivially by considering a real life example like JavaScript where all numbers are floats. Are there fewer types? Yes. Does it make working with numbers an absolute pain in the ass because of the ambiguity of APIs? Absolutely 100%.

Whether the statement holds for the specific case of *Fallible vs. Result* I find it hard to tell. It's nowhere near as clear cut as the JavaScript example obviously.

As for introducing function attributes and macros just to get rid of `Ok(())` within functions, well, I think I'd consider that a nuclear option.
